# This creates an Ingress in cluster 2 and associates it with a GSLB FQDN for AMKO
---
apiVersion: ako.vmware.com/v1beta1
kind: HostRule
metadata:
  name: cafe-gslb.vs4-2.rc.demo.avi.local
spec:
  virtualhost:
    fqdn: cafe-gslb.vs4-2.rc.demo.avi.local
    fqdnType: Exact
    gslb:
      fqdn: cafe-gslb.amko.rc.demo.avi.local
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cafe-gslb
  labels:
    app: gslb
spec:
  rules:
    - host: cafe-gslb.vs4-2.rc.demo.avi.local
      http:
        paths:
          - path: /tea
            pathType: Prefix
            backend:
              service:
                name: tea-svc
                port:
                  number: 8080
          - path: /coffee
            pathType: Prefix
            backend:
              service:
                name: coffee-svc
                port:
                  number: 8080
  tls:
    - hosts:
        - cafe-gslb.vs4-2.rc.demo.avi.local
      secretName: rc-wildcard-secret
