# This example creates an Ingress using the dedicated IngressClass (see dedicated-ingress-class.yaml)
# and also specifies a preferred IP address for the dedicated Ingress and both RSA/EC certificates
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cafe-ingress-dedicated
spec:
  ingressClassName: avi-ingress-dedicated
  rules:
  - host: cafe-dedicated.vs4.rc.demo.avi.local
    http:
      paths:
      - path: /tea
        pathType: Prefix
        backend:
         service:
          name: tea-svc
          port:
           number: 8080
      - path: /coffee
        pathType: Prefix
        backend:
         service:
          name: coffee-svc
          port:
           number: 8080
---
apiVersion: ako.vmware.com/v1beta1
kind: HostRule
metadata:
  name: hr-cafe-dedicated.vs4.rc.demo.avi.local
spec:
  virtualhost:
    fqdn: cafe-dedicated.vs4.rc.demo.avi.local
    fqdnType: Exact
    tls:
      sslKeyCertificate:
        name: Wildcard-RSA-Cert
        type: ref
        alternateCertificate:
          name: Wildcard-ECDSA-Cert
          type: ref
      termination: edge
    tcpSettings:
        loadBalancerIP: 10.206.112.93
